// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

export const meta = {
  user: {
    getSessionUser: { auth: 'required', type: 'query' },
  },
  wordLists: {
    createList: { auth: 'required', type: 'mutation' },
    deleteList: { auth: 'required', type: 'mutation' },
    getListById: { auth: 'required', type: 'query' },
    getUserLists: { auth: 'required', type: 'query' },
    restoreList: { auth: 'required', type: 'mutation' },
    updateList: { auth: 'required', type: 'mutation' },
  },
  _http: {},
} as const;

export type Meta = typeof meta;
