/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as ProfileSignOutRouteImport } from './routes/profile.sign-out'
import { Route as PracticeListIdRouteImport } from './routes/practice/$listId'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'
import { Route as DiscoverListIdRouteImport } from './routes/discover/$listId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSignOutRoute = ProfileSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => ProfileRoute,
} as any)
const PracticeListIdRoute = PracticeListIdRouteImport.update({
  id: '/practice/$listId',
  path: '/practice/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverListIdRoute = DiscoverListIdRouteImport.update({
  id: '/discover/$listId',
  path: '/discover/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRouteWithChildren
  '/discover/$listId': typeof DiscoverListIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/practice/$listId': typeof PracticeListIdRoute
  '/profile/sign-out': typeof ProfileSignOutRoute
  '/discover/': typeof DiscoverIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRouteWithChildren
  '/discover/$listId': typeof DiscoverListIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/practice/$listId': typeof PracticeListIdRoute
  '/profile/sign-out': typeof ProfileSignOutRoute
  '/discover': typeof DiscoverIndexRoute
  '/lists': typeof ListsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRouteWithChildren
  '/discover/$listId': typeof DiscoverListIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/practice/$listId': typeof PracticeListIdRoute
  '/profile/sign-out': typeof ProfileSignOutRoute
  '/discover/': typeof DiscoverIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/discover/$listId'
    | '/lists/$listId'
    | '/practice/$listId'
    | '/profile/sign-out'
    | '/discover/'
    | '/lists/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/discover/$listId'
    | '/lists/$listId'
    | '/practice/$listId'
    | '/profile/sign-out'
    | '/discover'
    | '/lists'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/discover/$listId'
    | '/lists/$listId'
    | '/practice/$listId'
    | '/profile/sign-out'
    | '/discover/'
    | '/lists/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  DiscoverListIdRoute: typeof DiscoverListIdRoute
  ListsListIdRoute: typeof ListsListIdRoute
  PracticeListIdRoute: typeof PracticeListIdRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/sign-out': {
      id: '/profile/sign-out'
      path: '/sign-out'
      fullPath: '/profile/sign-out'
      preLoaderRoute: typeof ProfileSignOutRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/practice/$listId': {
      id: '/practice/$listId'
      path: '/practice/$listId'
      fullPath: '/practice/$listId'
      preLoaderRoute: typeof PracticeListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/$listId': {
      id: '/discover/$listId'
      path: '/discover/$listId'
      fullPath: '/discover/$listId'
      preLoaderRoute: typeof DiscoverListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileSignOutRoute: typeof ProfileSignOutRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileSignOutRoute: ProfileSignOutRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRouteWithChildren,
  DiscoverListIdRoute: DiscoverListIdRoute,
  ListsListIdRoute: ListsListIdRoute,
  PracticeListIdRoute: PracticeListIdRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
