/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as PracticeListIdRouteImport } from './routes/practice/$listId'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeListIdRoute = PracticeListIdRouteImport.update({
  id: '/practice/$listId',
  path: '/practice/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/practice/$listId': typeof PracticeListIdRoute
  '/lists/': typeof ListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/practice/$listId': typeof PracticeListIdRoute
  '/lists': typeof ListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/practice/$listId': typeof PracticeListIdRoute
  '/lists/': typeof ListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lists/$listId' | '/practice/$listId' | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lists/$listId' | '/practice/$listId' | '/lists'
  id: '__root__' | '/' | '/lists/$listId' | '/practice/$listId' | '/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListsListIdRoute: typeof ListsListIdRoute
  PracticeListIdRoute: typeof PracticeListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$listId': {
      id: '/practice/$listId'
      path: '/practice/$listId'
      fullPath: '/practice/$listId'
      preLoaderRoute: typeof PracticeListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListsListIdRoute: ListsListIdRoute,
  PracticeListIdRoute: PracticeListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
